spring.application.name=ProductProjectForFileHandling

#Cloudinary configuration
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}

# data-base connectivity - 
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${USER_NAME}
spring.datasource.password=${PASSWORD}

# hibernate configuration - 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
